# Trainer config for multi-run RL integration test
max_concurrent_runs = 2
enable_token_export = true

[model]
name = "PrimeIntellect/Qwen3-0.6B-Reverse-Text-SFT"
seq_len = 65536
fused_lm_head_token_chunk_size = 8192
optim_cpu_offload = false

[model.lora]
rank = 8

[model.ac]
freq = 1

[model.compile]
fullgraph = false

[weight_broadcast]
type = "filesystem"
