seq_len = 32768

[log]
level = "debug"

[model]
name = "Qwen/Qwen3-30B-A3B-Thinking-2507"

[weight_broadcast]
type = "nccl"

[deployment]
type = "multi_node"
num_train_nodes = 2
num_infer_nodes = 2

[slurm]
job_name = "math-qwen30b"

[ckpt]
interval = 100

[wandb]
project = "qwen30b-math"

[trainer.model]
impl = "custom"
attn = "flash_attention_3"
ep = 8

[trainer.model.compile]

[trainer.model.ac_offloading]
max_inflight_activations = 5

[trainer.model.ac]
freq = 1

[trainer.optim]
type = "adamw"
lr = 1e-6

[orchestrator]
batch_size = 512
oversampling_factor = 2
max_off_policy_steps = 8

[orchestrator.train.sampling]
max_completion_tokens = 32768

[[orchestrator.train.source]]
name = "math"

[orchestrator.train.source.env.taskset]
id = "i3_math_v1"

[orchestrator.train.source.env.agent.harness]
id = "null"

[orchestrator.train.source.env.agent.runtime]
type = "subprocess"

[orchestrator.eval]
interval = 25

[[orchestrator.eval.source]]
name = "aime2025"

[orchestrator.eval.source.env.taskset]
id = "aime25-v1"

[orchestrator.eval.source.env.agent.harness]
id = "null"

[orchestrator.eval.source.env.agent.runtime]
type = "subprocess"

[inference.parallel]
tp = 8
