max_steps = 200
seq_len = 4096

[deployment]
num_train_gpus = 2
num_infer_gpus = 6

[model]
name = "Qwen/Qwen3-4B-Instruct-2507"

[wandb]
project = "wiki-search"
name = "wiki-search"

[trainer.optim]
lr = 1e-5
weight_decay = 0.0

[trainer.model.lora]
rank = 8
dropout = 0.0
target_modules = [
    "q_proj",
    "k_proj",
    "v_proj",
    "o_proj",
    "gate_proj",
    "up_proj",
    "down_proj"
]

[orchestrator]
batch_size = 512
group_size = 16
oversampling_factor = 2.0

[orchestrator.model.lora]
name = "qwen3-4b-wiki-search"

[orchestrator.train.sampling]
max_completion_tokens = 512

[[orchestrator.pre_batch_filters]]
type = "zero_advantage"
enforce = true

[[orchestrator.train.env]]
name = "wiki-search"
taskset = { id = "wiki-search-v1" }
harness = { id = "null", runtime = { type = "subprocess" } }

[ckpt] # Checkpoint at the end of training

[inference.model]
tool_call_parser = "hermes"
